version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dummyUser
      POSTGRES_PASSWORD: dummyPassword
      POSTGRES_DB: testdb
    ports:
      - 13307:5432
    volumes:
      - dummydb_data:/var/lib/postgresql/data

volumes:
  dummydb_data:
